default:
  parquetDirID: syn61250818
  archiveVersion: main/archive/2024-06-13/
  selectedVarsFileID: syn53503994
  outputDataDir: ./temp-output-data
  outputDataDirSleepSD: ./temp-output-data/sleepSD
  outputDataDirTimeInSleepStages: ./temp-output-data/timeInSleepStages
  outputDataDirPercentSleepStart: ./temp-output-data/percentSleepStart
  dailyMeasuresSynDirId: syn62668988
  sleepSDSynDirId: syn62782378
  timeInSleepStagesSynDirId: syn62782384
  percentSleepStartSynDirId: syn62782401
